# This file was generated by GoReleaser. DO NOT EDIT.
cask "lucenia" do
  version "0.1.3"

  on_macos do
    on_intel do
      sha256 "c009450e83e3e565de3407e1f38004805c8636f7762484294bcac700a4c76690"
      url "https://artifacts.lucenia.io/releases/cli/v#{version}/lucenia_#{version}_darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "23f52c23da04d76a14b7c0c92620faa4fe1da5375eb9137180448e10e877b00f"
      url "https://artifacts.lucenia.io/releases/cli/v#{version}/lucenia_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "a3e958b63059266fde53f712ede2824b1ac4876133952e6cfd858248be9cbb12"
      url "https://artifacts.lucenia.io/releases/cli/v#{version}/lucenia_#{version}_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "8b774347162f6ad6a659dedf7495c7ff890917322c1549dfa741aaaca2ed52d1"
      url "https://artifacts.lucenia.io/releases/cli/v#{version}/lucenia_#{version}_linux_arm64.tar.gz"
    end
  end

  name "lucenia"
  desc "Command-line client for Lucenia search clusters"
  homepage "https://lucenia.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lucenia"
  bash_completion "completions/lucenia.bash"
  fish_completion "completions/lucenia.fish"
  zsh_completion "completions/lucenia.zsh"

  # No zap stanza required

end
