# This file was generated by GoReleaser. DO NOT EDIT.
cask "lucenia" do
  version "0.1.3"

  on_macos do
    on_intel do
      sha256 "010159f7cf6971d92ebfb17bf5a4785e274756520a0c1efe6a5e617b57ad76c9"
      url "https://artifacts.lucenia.io/releases/cli/v#{version}/lucenia_#{version}_darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "2d93a7666ede4c568f056c3b836595e5b670225f97e7faa22e262a453e22568d"
      url "https://artifacts.lucenia.io/releases/cli/v#{version}/lucenia_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "58a807493eb34d22110c6f37c319fa361eb1061e97c0886e60b5592bb9dbe10f"
      url "https://artifacts.lucenia.io/releases/cli/v#{version}/lucenia_#{version}_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "b74f48be1f61efe54e7b9cde39ab19dfcdceca38bdf4af8c6235a3fb5e0d5cfb"
      url "https://artifacts.lucenia.io/releases/cli/v#{version}/lucenia_#{version}_linux_arm64.tar.gz"
    end
  end

  name "lucenia"
  desc "Command-line client for Lucenia search clusters"
  homepage "https://lucenia.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lucenia"
  bash_completion "completions/lucenia.bash"
  fish_completion "completions/lucenia.fish"
  zsh_completion "completions/lucenia.zsh"

  # No zap stanza required

end
