# This file was generated by GoReleaser. DO NOT EDIT.
cask "lucenia" do
  version "0.1.3"

  on_macos do
    on_intel do
      sha256 "17a288e4489634506847a7532b37567b5332fcf74ae8543a100fff9c0e7e7436"
      url "https://artifacts.lucenia.io/releases/cli/v#{version}/lucenia_#{version}_darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "bfa21ae7f52740fe543e77a6816e0b6b79e859378f5f51fd22a52cfebc2d1be2"
      url "https://artifacts.lucenia.io/releases/cli/v#{version}/lucenia_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "4c1e43732f82a8da30e4885a52119b6e6a5cca51f8c7af02046304e9c26b2d8d"
      url "https://artifacts.lucenia.io/releases/cli/v#{version}/lucenia_#{version}_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "9bdb929fc6de3ef1e3e86e5adbe8548c727819cbb6098d5d26989bc7a405ce3b"
      url "https://artifacts.lucenia.io/releases/cli/v#{version}/lucenia_#{version}_linux_arm64.tar.gz"
    end
  end

  name "lucenia"
  desc "Command-line client for Lucenia search clusters"
  homepage "https://lucenia.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lucenia"
  bash_completion "completions/lucenia.bash"
  fish_completion "completions/lucenia.fish"
  zsh_completion "completions/lucenia.zsh"

  # No zap stanza required

end
